spring.application.name=emp-task
spring.datasource.url=jdbc:postgresql://localhost:5432/emp_db
spring.datasource.username=postgres
spring.datasource.password=2662
spring.jpa.hibernate.ddl-auto=update
spring.jpa.open-in-view=false
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

